drop table batch;            
drop table block_content;                
drop table block_content__body ;         
drop table block_content_field_data ;    
drop table block_content_field_revision ;
drop table block_content_revision;      
drop table block_content_revision__body; 
drop table cache_bootstrap;              
drop table cache_config ;                
drop table cache_container ;             
drop table cache_data;                   
drop table cache_default ;               
drop table cache_discovery ;             
drop table cache_entity;                 
drop table cachetags ;                   
drop table comment ;                     
drop table comment__comment_body  ;      
drop table comment_entity_statistics   ; 
drop table comment_field_data ;          
drop table config    ;                   
drop table file_managed  ;               
drop table file_usage ;                  
drop table key_value ;                   
drop table key_value_expire   ;          
drop table menu_tree  ;                  
drop table node      ;                   
drop table node__body   ;                
drop table node_access    ;              
drop table node_field_data     ;         
drop table node_field_revision ;         
drop table node_revision     ;           
drop table node_revision__body  ;        
drop table queue;                        
drop table router      ;                 
drop table semaphore ;                   
drop table sequences  ;                  
drop table sessions   ;                  
drop table url_alias   ;                 
drop table user__roles ;                 
drop table users      ;                  
drop table users_data   ;                
drop table users_field_data     ;        
drop table history;
drop table menu_link_content    ;
drop table menu_link_content_data    ;
drop table node__comment           ;
drop table node__field_image      ;
drop table node__field_tags      ;
drop table node_revision__comment   ;
drop table node_revision__field_image;
drop table node_revision__field_tags;
drop table search_dataset  ;
drop table search_index  ;
drop table search_total ;
drop table shortcut ;
drop table shortcut_field_data ;
drop table shortcut_set_users ;
drop table taxonomy_index ;
drop table taxonomy_term_data ;
drop table taxonomy_term_field_data;
drop table taxonomy_term_hierarchy ;
drop table user__user_picture ;
drop table watchdog    ;